inherit_from: .rubocop_todo.yml

AllCops:
  Excludes:
  - Guardfile
  - Rakefile
  - Gemfile
  - node_modules/**/*.*
  - db
  - bin/bundle
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Max: 125
